### ISSUE TITLE
*** Wishlist ***

### ISSUE THREAD

**Issue by kernelsauce** [kernelsauce/turbo#119]
Hi all.

Please let's hear all your wishes for future releases!

v1.1 (current master branch) will have full WebSockets support (client and server).

**Comment by YuanPeir-Chen** [comment]
Hi, I develop some application with turbolua, and if I use capital letter in URL as follow

turbo.web.Application:new({
    {"^/HelloWorld$", MyHelloWorldHandler}
}):listen(8888)

the browser will show the 404 page not found!

Does the URL cannot use capital letter??

**Comment by kernelsauce** [comment]
v1.x the url needs to be lowercase and the input URL from the browser
is lowercased before matching. So it is case insensitive somewhat.

in the new v2.x it is case sensitive, so you can use /HelloWorld and
also use this in your browser and it will work. v2.x is currently in
master.

2015-05-13 4.27 GMT+02.00, YuanPeir-Chen <notifications@github.com>:
> Hi, I develop some application with turbolua, and if I use capital letter in
> URL as follow
>
> turbo.web.Application:new({
>     {"^/HelloWorld$", MyHelloWorldHandler}
> }):listen(8888)
>
> the browser will show the 404 page not found!
>
> Does the URL cannot use capital letter??
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/kernelsauce/turbo/issues/119#issuecomment-101485725


-- 
Best regards/Vennlig hilsen
John Abrahamsen
Mobile: (+47) 945 40 425

**Comment by kernelsauce** [comment]
So v2.0 is getting ready to be wrapped up for a Beta release soon with the main feature being Windows support (and LuaSocket support).

If there are any other features you would want please speak up now. :)

**Comment by aellwein** [comment]
Hi John,
does turbolua support HTTP caching in form of If-Modified-Since and 304 Not Modified responses? 
I think it is an important feature. Tornado does much about this.
And yes, +1 for async SQLite module. This would make a nice addition to turbolua...

**Comment by kernelsauce** [comment]
Turbo uses Etag for static files, which will give 304's. The rest is up to the user to implement in his application really. Its supported, but not implemented :).

**Comment by aellwein** [comment]
Cool, thanks!

**Comment by YuanPeir-Chen** [comment]
Hi John

Does turbolua support http & https at the same time but with different port?
I mean dose script can support to put below command or something like this?

   turbo.web.Application({
        {"^/Test$", TestHandler},
    }):listen(80, nil ,{max_body_size =1024*1024*1}) -- for http
      :listen(443, nil ,{max_body_size =1024*1024*1 ,   --for https
                    ssl_options = {
                        key_file = "./sslkeys/server.key",
                        cert_file = "./sslkeys/server.crt"}
                    })

**Comment by kernelsauce** [comment]
Yes, it does. 

But you need to use two Application (or HTTPServer) objects.

```
local app1 = turbo.web.Application({
    {"^/$", MyHandler}
}):listen(443, nil, {
    ssl_options = {
        key_file = "./sslkeys/server.key",
        cert_file = "./sslkeys/server.crt"
    }
})

local app2 = turbo.web.Application({
    {"^/$", MyHandler}
}):listen(80)

turbo.ioloop.instance():start()
```

**Comment by javatmn** [comment]
I also like to have an async SQLite DB backend support, also thank you a lot for this great project!

**Comment by kernelsauce** [comment]
I think SQLite would best be suited as a seperate module to reduce complexity.
