### ISSUE TITLE
Is 1.1 still active?

### ISSUE THREAD

**Issue by Mynock17** [kernelsauce/turbo#147]
Hi, 

im starting a big project and looking for a luajit server-framework. 
Is the work for v1.1 ongoing?

Regards
Bernd

**Comment by kernelsauce** [comment]
1.1beta6 is assumed to be stable, but still in beta.

I will probably create a release final version soon.

**Comment by kernelsauce** [comment]
I have created a final release for v1.1. Tagged as v1.1.
