### ISSUE TITLE
mustache functionalty

### ISSUE THREAD

**Issue by alisabri** [kernelsauce/turbo#148]
Hi John,
First, thanks for your efforts for turbo. I'm planning to use turbo for an application on an embedded device and for the moment it looks like the only proper choice. 

Anyway, the issue is about mustache implementation. It looks like it does not support "functions" for "sections", so
```javascript
local tst = "{{#bold}}Hi {{name}}.{{/bold}}"

local hash = {
   name = "Tater",
   bold = function (text, render)
      return "<b>" .. render(text) .. "</b>"
   end
}
print(mustache.render(tst, hash))
```
outputs : Hi Tater.

it just evaluates sections as conditional, does it?

**Comment by kernelsauce** [comment]
Hi. Yes, you are correct. Sections does not accept functions at the moment, only values like {{name}} accepts functions. It would probably be easy to add support so that section works with functions  though.

**Comment by alisabri** [comment]
Hi,
I will play a bit with mustache.lua Let you know if I can manage.

Regards,
