### ISSUE TITLE
turbovisor reloading your browser

### ISSUE THREAD

**Issue by rjpcomputing** [kernelsauce/turbo#172]
Can turbovisor reload the page in your browser when it detects a file change?

**Comment by ddysher** [comment]
IIRC, it doesn't reload the page in browser.

**Comment by rjpcomputing** [comment]
I was meaning could it be made to plugin to a system like this: http://livereload.com/

**Comment by kernelsauce** [comment]
You would need to signal the browser then and handle the signal with Js. Anything is possible. This is best left up to the user of the framework to handle. Most of the time I find F5 works best :)

**Comment by rjpcomputing** [comment]
OK. I just think this would really polish and make this world class. I saw a few examples of it in action and I love Turbo and was just feeling like it could find a home in turbovisor. If I ever get an itch maybe I will try to impliment it. Thanks.
