### ISSUE TITLE
Mustache partials not being rendered

### ISSUE THREAD

**Issue by essenciary** [kernelsauce/turbo#174]
I'm trying to render partials in Mustache, but without any luck so far. I've tried everything, I can't get the renderer to display the partial. 

A very basic example based on the included Turbo Mustache example - I just moved a part of the template into a partial and provided it as the 3rd param to Mustache.render. Does not work. 

https://gist.github.com/ce5d2700cb49f19fc358

**Comment by essenciary** [comment]
Any luck with this? Am I doing something wrong maybe? Thanks!

**Comment by kernelsauce** [comment]
I have not had the time yet. I looked at another issue yesterday.

**Comment by kernelsauce** [comment]
This is now fixed in master.

https://gist.github.com/kernelsauce/48dd4c5023d443cb57ae works as expected. Please retry your things.

**Comment by essenciary** [comment]
Works like a charm, thanks! 

The only gotcha is that in order to work, Turbo Mustache expects a syntax like
`{{>next_more}}`
(no space between ">" and the name of the template)
while the best practice seems to be to write it as
`{{> next_more}}`

It would be good to support the version with space too - or at least warn in the docs about the required syntax. 

Cheers!

**Comment by kernelsauce** [comment]
Ok. I will fix  the parser.

**Comment by kernelsauce** [comment]
Fixed https://github.com/kernelsauce/turbo/commit/1dc688a828ff49a7da20a8052cb7536506fc53c2

**Comment by essenciary** [comment]
Thank you very much John!
