### ISSUE TITLE
IOStream:write issue

### ISSUE THREAD

**Issue by shadylabs** [kernelsauce/turbo#179]
Hi, I have this problem with IOStream:write (data, callback, arg).
According to documentation the callback is called after write is over so i would like to use it to close the stream after writing to it once. After some experiments it looks like the callback /or closing function/ was executed before even writing begins. Then i decided to check the stream if it is writing and instead of true or false i received nil. This was checked again with the "Parrot" example too. This thingy here:
**function iostream.IOStream:writing()
       return self._write_buffer_size ~= 0 or self._const_write_buffer
end**
for some reason returns nil. Any suggestions will be highly appreciated
Plamen.

**Comment by kernelsauce** [comment]
You resolved this @shadylabs ?

**Comment by shadylabs** [comment]
yeah. its probably my mistake, just replaced some functions and it works properly know. Working on the code more than 10 hours a day results in lots off errors , sorry about that.
