### ISSUE TITLE
TURBO_SOCKET_BUFFER_SZ 

### ISSUE THREAD

**Issue by GeorgeVV** [kernelsauce/turbo#180]
I get a warning message that says :   
"Max buffer size could not be set to lower value than  TURBO_SOCKET_BUFFER_SZ (17416B)
 What does it meaning ?.  How can I treat this warning ?
Where I set other value ?.

**Comment by kernelsauce** [comment]
What version are you running? I have removed this warning in master as it does not really matter at all, unless you are doing very specific things :). Its the internal workings in the HTTP server that adjusts the buffer sizes too low to avoid e.g. header attacks. Do not worry about them...

**Comment by GeorgeVV** [comment]
I use the following version of turbo : 1.1.0
 - information with luarocks :               sudo luarocks show turbo: 1.1-0
 -  information with the variable turbo.VERSION : 1.1.0
 I found the class with the warning message: /usr/local/share/luajit-2.0.2/turbo/iostream.lua. 
 Yes, it's only a warning message :).  
I've several tests with turbo, for the moment all works fine.

**Comment by kernelsauce** [comment]
Yes, this is nothing to worry about. Once v2.0 (soon) hits LuaRocks it will no longer display this warning.
