### ISSUE TITLE
XSS in error page

### ISSUE THREAD

**Issue by nagadomi** [kernelsauce/turbo#182]
```lua
local turbo = require("turbo")
local TestHandler = class("TestHandler", turbo.web.RequestHandler)
function TestHandler:get()
   -- e.g. error("error: " .. self:get_argument("name"))
   error('<script type="text/javascript">alert("foobar")</script>')
end
local app = turbo.web.Application:new({
    {"/", TestHandler}
})
app:listen(8888)
turbo.ioloop.instance():start()
```
https://github.com/kernelsauce/turbo/blob/master/turbo/web.lua#L1206 needs HTML escape.

**Comment by kernelsauce** [comment]
Good catch @nagadomi. I will correct this asap.

**Comment by kernelsauce** [comment]
Fixed by commit in https://github.com/kernelsauce/turbo/commit/b39aad5f2b45485f427abcccb46a77e1ecd16a49

Will create a v1.1.3 also based on these changes.

**Comment by kernelsauce** [comment]
Luarocks also now serves v1.1.3 with the fix.
