### ISSUE TITLE
TCP client example.

### ISSUE THREAD

**Issue by shadylabs** [kernelsauce/turbo#184]
Hi,
I can't figure this magic number "fd" in  **IOStream(fd, io_loop, max_buffer_size)**.  How do i get the number to use it in IOStream instantiation. Is there a chance of small example for implementing simple TCP client as it was done for the TCP server in "Parrot.lua".
As was thinking i need to create stream instance, then to connect the created instance to server  then use the supplied methods to read and write with their respective callbacks. It looks only thing i have no idea how to get is the "fd" to use it for my instance.
Plamen.

**Comment by kernelsauce** [comment]
local sock, msg = turbo.socket.new_nonblock_socket(
		 turbo.socket.AF_INET,
		 turbo.socket.SOCK_STREAM)
	if sock == -1 then
	 	error("Could not create socket. " .. msg)
	end

	local iostream = turbo.iostream.IOStream(sock)

or you could use the new "simple" IO model that currently is in the master branch and will be in v2.0:

https://github.com/kernelsauce/turbo/blob/master/spec/iosimple_spec.lua

This one also is callbackless and more readable...

**Comment by shadylabs** [comment]
Thanks,
I knew it will be something about the creating a socket, but my approach was wrong apparently.
