### ISSUE TITLE
[Question]Problems running the helloworld.lua example

### ISSUE THREAD

**Issue by SanjanaSridhar** [kernelsauce/turbo#185]
Hello,
I am not sure if this is the right place to ask this question, if it is not please let me know where i should be asking it.

I am just getting started with turbo and i'm trying to run the helloworld.lua example, but I keep getting the following error:

/usr/local/share/lua/5.1/turbo/ioloop.lua:49: Could not load a poll module. Make sure you are running this with  LuaJIT. Standard Lua is not supported.

Even though I am running it with luajit. I also have [Torch](http://torch.ch/) installed - maybe this is what is causing the problem?
Running this on Ubuntu 14.04

Thanks

**Comment by kernelsauce** [comment]
Are you running it using luajit and not lua?

**Comment by SanjanaSridhar** [comment]
Hello

Thanks for getting back to me. I managed to fix it. It's just that torch had installed luajit in another path which wasn't being recognized by Turbo.

**Comment by btabibian** [comment]
Hello @SanjanaSridhar, I am having a similar problem. Could you please tell me how you solved the problem.

**Comment by SanjanaSridhar** [comment]
Hello @btabibian,

I just had to run it as `torch helloworld.lua`. Hope this helps
