### ISSUE TITLE
Running lua scripts through get request

### ISSUE THREAD

**Issue by SanjanaSridhar** [kernelsauce/turbo#186]
Hello is it possible to run a lua script through the get request?

Thanks

**Comment by kernelsauce** [comment]
What do you want to do? Run a Lua script that comes in as a argument in  a GET request? Or run a Lua script when you get a GET request?

**Comment by SanjanaSridhar** [comment]
I want to run a lua script when I get a GET request. Thank you.

**Comment by kernelsauce** [comment]
Well Lua has a builtin function for just that. Running it in the context of GET request in Turbo doesnt really change anything:

http://www.lua.org/manual/5.2/manual.html#pdf-loadfile

loadfile ([filename [, mode [, env]]])

Similar to load, but gets the chunk from file filename or from the standard input, if no file name is given.

**Comment by SanjanaSridhar** [comment]
Thank you so much!
