### ISSUE TITLE
For Windows Beta of turbo.lua is ssl support working?

### ISSUE THREAD

**Issue by agrw** [kernelsauce/turbo#188]
C:\turbo.lua\src\turbo\examples>luajit static.lua
[util.lua] Could not load rt.so, falling back to gettimeofday.
[W 2015/05/06 19:25:11] Not Linux, using LuaSocket (degraded performance).
luajit: C:\turbo.lua\src\turbo\turbo\crypto_luasec.lua:24: module 'ssl' not found:
        no field package.preload['ssl']
        no file 'C:\turbo.lua\rocks\share\lua\5.1\ssl.lua'
        no file 'C:\turbo.lua\rocks\share\lua\5.1\ssl\init.lua'
        no file 'C:\turbo.lua\src\turbo\ssl.lua'
        no file 'C:\turbo.lua\src\turbo\turbo\ssl.lua'
        no file 'C:\turbo.lua\rocks\lib\lua\5.1\ssl.dll'
stack traceback:
        [C]: in function 'require'
        C:\turbo.lua\src\turbo\turbo\crypto_luasec.lua:24: in main chunk
        [C]: at 0x07fef5e15e30
        [C]: in function 'require'
        C:\turbo.lua\src\turbo\turbo\iostream.lua:33: in main chunk
        [C]: in function 'require'
        C:\turbo.lua\src\turbo\turbo\tcpserver.lua:21: in main chunk
        [C]: in function 'require'
        C:\turbo.lua\src\turbo\turbo.lua:105: in main chunk
        [C]: in function 'require'
        static.lua:18: in main chunk
        [C]: at 0x013f872000

**Comment by kernelsauce** [comment]
Hi. 

Yes, it works, but you need to install LuaSec (https://luarocks.org/modules/luarocks/luasec) for it to work. Sorry about the missing documentation for this, but it is still in beta, so it will probably be in the docs when the time for Turbo 2.0 comes. :)

You need the OpenSSL source to compile that module btw.

**Comment by agrw** [comment]
ok thanks
