### ISSUE TITLE
About uploads files?

### ISSUE THREAD

**Issue by YuanPeir-Chen** [kernelsauce/turbo#192]
Hi John

I reference issue #158 (Does Turbo support file uploads #158) for support file uploads.
My question is when I upload a png file(160492 bytes), and it seem everything is ok, 
but whem I use HxD to view a receive file(received 160790 byte), it has some extra information in the begin and ending in the receive file
like this:

begin>>
------------------------------435194b1263d..Content-Disposition: form-data; name="upload"; filename="mario.png"..Content-Type: application/octet-stream....

ending>>
..------------------------------435194b1263d--..

How can I receive the file(without extra information) that as same as I upload without extra information ??

The code:
```
function MyHandler:post()
    local file = self:get_argument("file", "ERROR")
    self:write("(POST Action) FILE ")
    local fd1 = io.open("output1","w+")
    io.output(fd1)
    io.write(self.request.body)
    io.close(fd1)
 
end
```

and the other question is what is the best way to get the file name of the upload?
I didn't see the solution on issue #158 about @EstebanSannin ask you ??

Thanks

**Comment by kernelsauce** [comment]
What version? I will look at it later.

**Comment by YuanPeir-Chen** [comment]
I use the version of turbo there on github master, and the version in turbo.lua is 

turbo.MAJOR_VERSION = 2
turbo.MINOR_VERSION = 0
turbo.MICRO_VERSION = 0

**Comment by kernelsauce** [comment]
Still have not had the time, a lot to do these days. I will try looking at it tomorrow.

**Comment by kernelsauce** [comment]
Yes,  I have not tested this myself...

local turbo = require "turbo"

MyHandler = class("MyHandler", turbo.web.RequestHandler)

function MyHandler:post()
    local file = self:get_argument("file", "ERROR")
    self:write("(POST Action) FILE ")
    local fd1 = io.open("output1.jpg","wb")
    io.output(fd1)
    io.write(file)
    io.close(fd1)
end


-- Create an Application object and bind our HelloWorldHandler to the route '/hello'.
local app = turbo.web.Application:new({
    {"/", MyHandler}
})

-- Set the server to listen on port 8888 and start the ioloop.
app:listen(8888, "127.0.0.1", {max_body_size=1024*1024*100})
turbo.ioloop.instance():start()

**Comment by kernelsauce** [comment]
Sorry, a lot of typos in the first post. Edited :).

**Comment by YuanPeir-Chen** [comment]
Hi Jhon,

I create a empty file, and use test code which you post here.

Unfortunately, I still get the error file which called outpu1.jpg and it size is only 5 bytes.
It content is 45 52 52 4F 52(ERROR), this 5 bytes is given from second parameter that I give in self:get_argument()

I still got the "nil" from args and t in web.lua.

Maybe I made some mistake to use turbolua?
Actually, I use curl to test this function, and it's command is 
`curl -F "image=@/home/user/Desktop/jpeg.jpeg" 127.0.0.1:8888/`
then I can received the response 
`[S 2015/06/20 09:12:16] [web.lua] 200 OK POST/ (127.0.0.1) 40ms `
can you describe your test method??

thanks!

**Comment by YuanPeir-Chen** [comment]
Sorry, I think I made mistake to use turbolua.

if I uploaded via a 
`curl -F "file=@/home/user/Desktop/jpeg.jpeg" 127.0.0.1:8888/`
it's successfully saves a JPG image .

thanks!
