### ISSUE TITLE
SSL on Linux is broken

### ISSUE THREAD

**Issue by luastoned** [kernelsauce/turbo#196]
I updated Turbo to the latest master today and could not run any of my apps, including examples.
Tested on two separate Ubuntu 14.04 servers, both times the same result:

	/turbo/examples > luajit githubfeed.lua
	[E 2015/07/13 10:05:08] [ioloop.lua] Error in IOLoop handler.
	▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼
	/turbo/crypto_linux.lua:247: SSL certificate chain validation failed: unable to get local issuer certificate
	stack traceback:
			[C]: in function 'error'
			/turbo/crypto_linux.lua:247: in function 'ssl_do_handshake'
			/turbo/iostream.lua:1197: in function '_do_ssl_handshake'
			/turbo/iostream.lua:1213: in function '_handle_read'
			/turbo/iostream.lua:484: in function </turbo/iostream.lua:475>
			[C]: in function 'xpcall'
			/turbo/ioloop.lua:517: in function '_run_handler'
			/turbo/ioloop.lua:434: in function '_event_poll'
			/turbo/ioloop.lua:423: in function 'start'
			githubfeed.lua:54: in main chunk
			[C]: at 0x0804c240
	▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲

	/turbo/examples > luajit sslserver.lua
	[E 2015/07/13 10:04:02] [ioloop.lua] Error in IOLoop handler.
	▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼
	/turbo/crypto_linux.lua:290: Could not do SSL handshake. SSL error. error:1407609C:SSL routines:SSL23_GET_CLIENT_HELLO:http request
	stack traceback:
			[C]: in function 'error'
			/turbo/crypto_linux.lua:290: in function 'ssl_do_handshake'
			/turbo/iostream.lua:1197: in function '_do_ssl_handshake'
			/turbo/iostream.lua:1213: in function '_handle_read'
			/turbo/iostream.lua:484: in function </turbo/iostream.lua:475>
			[C]: in function 'xpcall'
			/turbo/ioloop.lua:517: in function '_run_handler'
			/turbo/ioloop.lua:434: in function '_event_poll'
			/turbo/ioloop.lua:423: in function 'start'
			sslserver.lua:35: in main chunk
			[C]: at 0x0804c240
	▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲

**Comment by luastoned** [comment]
I was able to track it down to 5ee6726e8040be83acedf89a7ee09caca6d42d04, before that all examples worked.

**Comment by kernelsauce** [comment]
Thank you for reporting. Will correct it.
man. 13. jul. 2015 kl. 11.25 skrev Gregor Steiner <notifications@github.com
>:

> I was able to track it down to 5ee6726
> <https://github.com/kernelsauce/turbo/commit/5ee6726e8040be83acedf89a7ee09caca6d42d04>,
> before that all examples worked.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kernelsauce/turbo/issues/196#issuecomment-120867784>.
>
-- 
Mvh / Best regards
John Abrahamsen
Tlf/Phone: (+47) 941 35 009

**Comment by luastoned** [comment]
Okay, here is the code flow:
	app.lua -> async.HTTPClient():fetch()
	async.lua #283 ->
		-- ssl_options are never set when you do a normal fetch()
		self.ssl_options = self.ssl_options or {}
		-- calls create_client_context with verify_ca = nil
		crypto.ssl_create_client_context(..., self.ssl_options.verify_ca)
	crypto_linux.lua #140 ->
		-- this part is never called, thus certs are never loaded
		if verify == true then
			if lssl.SSL_CTX_load_verify_locations(ctx, ca_cert_path, nil) ~= 1 then
				err = lssl.ERR_peek_error()
				lssl.ERR_clear_error()
				return err, crypto.ERR_error_string(err)
			end
			lssl.SSL_CTX_set_verify(ctx, crypto.SSL_VERIFY_PEER, nil);
		end
	async.lua #310 ->
		local rc, msg = self.iostream:connect(..., self.ssl_options.verify_ca, ...)
	iostream.lua #1166 ->
		-- now verify gets set to true which causes everything past that to fail
		self._ssl_verify = verify == nil and true or verify

**Comment by luastoned** [comment]
I also noticed libtffi_wrap not loading on a clean Ubuntu 14.04 (no LuaJIT / Turbo prior installed).

**Comment by kernelsauce** [comment]
Should be fixed in master now. As to not loading that is because of change I know of. I am looking at a work around for that too.

**Comment by kernelsauce** [comment]
Loading of libtffi_wrap should be fixed in master now, using the old way in addition to new ways.

**Comment by luastoned** [comment]
```
name = name or os.getenv("TURBO_LIBTFFI") or "libtffi_wrap"
-- But only if name is not given as argument.
if not name and not ok then
    ok, lib = pcall(ffi.load, "/usr/local/lib/libtffi_wrap.so")
end
```

The old way will never get invoked, the whole if statement is redundant (not ok checked twice).
