### ISSUE TITLE
LIBTFFI not loading on Linux / Ubuntu

### ISSUE THREAD

**Issue by luastoned** [kernelsauce/turbo#197]
The problem exists because Ubuntu does not set `LD_LIBRARY_PATH` but uses `ldconfig`

The old way will never get invoked, the whole if statement is redundant (not ok checked twice).

```
name = name or os.getenv("TURBO_LIBTFFI") or "libtffi_wrap"
-- But only if name is not given as argument.
if not name and not ok then
    ok, lib = pcall(ffi.load, "/usr/local/lib/libtffi_wrap.so")
end
```

**Comment by kernelsauce** [comment]
Oh, thank you. Thats a bad one on me. Should be corrected in master now. Please verify @luastoned.

**Comment by luastoned** [comment]
:+1:
