### ISSUE TITLE
Mac Support

### ISSUE THREAD

**Issue by JaredSartin** [kernelsauce/turbo#201]
Hey, this is a feature request... Over a year ago it looked like people were attempting mac support. Wondering what the status is on this? Would love to have it!!

**Comment by kernelsauce** [comment]
Hi @JaredSartin. Are you thinking about this for development purposes or for production?

**Comment by kernelsauce** [comment]
You can now install turbo on OS X by running
``sudo make install``

Use Luarocks to install LuaSocket and LuaSec for OpenSSL support.

This is for development as I consider LuaSockets polling to be too slow for production.

**Comment by JaredSartin** [comment]
Awesome! It is for development. I didn't look too far after luarocks
errored out.

Maybe it should be more explicit in the read me?

**Comment by kernelsauce** [comment]
LuaRocks will not work at the moment as that is set up with v1.1.4 the current stable version.
OSX support is in v2.0. :)

**Comment by JaredSartin** [comment]
Ah! Sweet. Can't wait to get home and start trying it all out!

**Comment by kernelsauce** [comment]
OSX is now supported through LuaSocket/LuaSec. All Mac users please test :).
