### ISSUE TITLE
"SSL certficate hostname validation failed" even when SSL validation is turned off

### ISSUE THREAD

**Issue by fuxoft** [kernelsauce/turbo#204]
Sorry about potentially stupid question but In release 1.1-4 (Linux), when I try to use HTTPClient for a https: numeric IPv4 address (e.g. "https://149.154.167.200/index.htm"), I get the following error even when I have "verify_ca" parameter set to false, i.e. I *don't want* validation: 

```
crypto.lua:657: SSL certficate hostname validation failed, rc 1
```

When using non-numeric address (e.g. "https://api.telegram.org"), there are no errors.

I was implementing my own DNS caching to make my HTTPS requests quicker and now I am puzzled how to use HTTPS requests with numeric addresses. When using numeric HTTPS addresses in Luasocket & LuaSec, it works without errors.

**Comment by kernelsauce** [comment]
That is strange. I will have a look at it. Thank you for reporting.
søn. 19. jul. 2015 kl. 20.37 skrev Frantisek Fuka <notifications@github.com
>:

> Sorry about potentially stupid question but In release 1.1-4 (Linux), when
> I try to use HTTPClient for a https: numeric IPv4 address (e.g. "
> https://149.154.167.200/index.htm"), I get the following error even when
> I have "verify_ca" parameter set to false, i.e. I *don't want*
> validation:
>
> crypto.lua:657: SSL certficate hostname validation failed, rc 1
>
> When using non-numeric address (e.g. "https://api.telegram.org"), there
> are no errors.
>
> I was implementing my own DNS caching to make my HTTPS requests quicker
> and now I am puzzled how to use HTTPS requests with numeric addresses. When
> using numeric HTTPS addresses in Luasocket & LuaSec, it works without
> errors.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kernelsauce/turbo/issues/204>.
>
-- 
Mvh / Best regards
John Abrahamsen
Tlf/Phone: (+47) 941 35 009

**Comment by kernelsauce** [comment]
Fix is now in v1.1.5 which can be downloaded as tar ball from here, or installed with luarocks (just pushed).

**Comment by kernelsauce** [comment]
Just to add, this is not pulled upstream as master already had revised code in that section that worked as expected.

**Comment by fuxoft** [comment]
Seems to work perfeclty now. Thanks.
