### ISSUE TITLE
response:get_url() from an async request  causes a segfault

### ISSUE THREAD

**Issue by luastoned** [kernelsauce/turbo#208]
local res = local res = coroutine.yield(turbo.async.HTTPClient():fetch("http://google.com"))
    print(res.headers:get_url())

    [S 2015/07/24 11:28:18] [async.lua] GET www.google.com:80/ => 200 OK 123ms
    Segmentation fault

**Comment by kernelsauce** [comment]
Thanks for the report. I will investigate it.

**Comment by luastoned** [comment]
The docs also state that `res.headers` should be a `HTTPHeaders` instance, which does not seem to be true.

**Comment by kernelsauce** [comment]
Nop, its a HTTPParser instance. It was changed at some point...

**Comment by luastoned** [comment]
Updating `http-parser` from `2.1` to `2.5` seems to fix the issue.

Can we have information about the request-headers (assuming we get redirected) ?

There is no way to tell what site we landed on following any url-shortener at the moment.

**Comment by kernelsauce** [comment]
Doesn't really help to upgrade the version to fix segfault, there is something else at play.

**Comment by kernelsauce** [comment]
In master you will no longer get a segfault from this. The problem is that the URL is never set in HTTPParser when parsing responses... Instead we now raise a error saying that the value is not inited for responses. The new .url attribute should be used instead.

**Comment by kernelsauce** [comment]
To add, you can still use HTTPParser for this, by using parse_url() and get_url_field() of the HTTPParser class.
