### ISSUE TITLE
Get the user agent request header

### ISSUE THREAD

**Issue by clandmeter** [kernelsauce/turbo#209]
I've been reading the documentation, but i have no idea how I would be able to get the user agent inside my turbo application. 
I would like to filter on the User-Agent in one of my RequestHandlers. How would one do this?

P.S. There also seems to be a typo in the docs for which I created a PR #207 (if i'm not mistaken)

**Comment by kernelsauce** [comment]
Like this you mean?

``` 
    local agent_string = self.request.headers:get("User-Agent")
```
Use self.request.headers:get("User-Agent", true) for case-insensitive matching.

**Comment by kernelsauce** [comment]
Also you can refer to this in the docs for more info:

https://turbo.readthedocs.org/en/latest/httpserver.html#httprequest-class

**Comment by clandmeter** [comment]
Yes, this seems to work Thanks!. 
I'm rather new to Lua Turbo and its oo interface, so its little hard for me to find out how to access these functions from within other parts of the framework ie RequestHandler. Is there some documentation about how to access them?

**Comment by kernelsauce** [comment]
For RequestHandler you should read this:

https://turbo.readthedocs.org/en/latest/web.html

All of the public API should be documented.
