### ISSUE TITLE
allow_redirects is not true by default even though the docs state otherwise

### ISSUE THREAD

**Issue by luastoned** [kernelsauce/turbo#210]
turbo.async.HTTPClient():fetch("http://google.com", {allow_redirects = true})

**Comment by luastoned** [comment]
`use_gzip` is another arg that should be true but is never used.

**Comment by kernelsauce** [comment]
gzip is not yet supported at all so it doesn't really matter, ideally it should be removed from docs until supported. Im trying to include it in v2.0, but no promises...
