### ISSUE TITLE
WebSocketHandler locks up everything if message size >125 characters

### ISSUE THREAD

**Issue by Raeon** [kernelsauce/turbo#218]
Running Chromium on Arch Linux.

Code for "test.lua" in the top right, "luajit test.lua" in the bottom right, and the JavaScript console in Chromium on the left half of the screen:
![](http://i.imgur.com/IBUR14b.png)

Do note that Array(x).join always returns 1 character less than 'i' as demonstrated in the bottom left of the image.

**Comment by kernelsauce** [comment]
Hi. Thanks for reporting, I will investigate this issue.

**Comment by kernelsauce** [comment]
Oh btw, is this on x64 arch?

**Comment by Raeon** [comment]
It is.

**Comment by kernelsauce** [comment]
I guess this is v1.1.*? There has been bug fixes in v2.0 that fixes these things but they have not been merged into older versions. I will create a new release for this now.

**Comment by kernelsauce** [comment]
Please try this:

https://github.com/kernelsauce/turbo/releases/tag/v1.1.6

or reinstall with LuaRocks.

**Comment by Raeon** [comment]
After updating from 1.1.5 to 1.1.6 via LuaRocks, this issue has been resolved. Thank you very much for making and updating this project! :+1:
