### ISSUE TITLE
Add support for session cookies (and other optional attributes)

### ISSUE THREAD

**Issue by zcsteele** [kernelsauce/turbo#220]
Turbo currently only supports standard cookie types; there is no documented API call for cookie management to support session cookies or any of the other optional attributes (such as 'secure' or 'HttpOnly').  Turbo should have support for generating cookies with these settings.

I have started working on a fork expanding the cookie functionality in Turbo - https://github.com/zcsteele/turbo/tree/session-cookie.  Any comments/criticisms would be appreciated.

**Comment by kernelsauce** [comment]
Hi. You are correct there is no session cookies, that is up to the user to create as in Tornado. If you add more features then please send a pull request and it will be included (provided the code is good).
