### ISSUE TITLE
HTTPClient has nil as body

### ISSUE THREAD

**Issue by clandmeter** [kernelsauce/turbo#222]
I have the below code in my project to do recaptcha verifications.
Since i upgraded from 1.1.6 to 2.0.0 this function fails to decode json (nil value supplied).
As there is no res.error, i assume something goes wrong providing the body of the message?

```
function RecaptchaVerify(response)
    local uri = "https://www.google.com/recaptcha/api/siteverify"
    local kwargs = {}
    kwargs.method = "POST"
    kwargs.params = {
        secret = conf.rc.secret,
        response = response
    }
    local res = coroutine.yield(turbo.async.HTTPClient():fetch(uri, kwargs))
    if res.error then
        return false
    end
    local result = turbo.escape.json_decode(res.body)
    return result.success
end
```

**Comment by kernelsauce** [comment]
Hmm. Thats strange. Will investigate that.

**Comment by kernelsauce** [comment]
Fixed.  New release v2.0.1.

**Comment by kernelsauce** [comment]
Available on luarocks, Github etc.

**Comment by clandmeter** [comment]
Thanks John.

I'll push a new version and it works: http://pkgs.alpinelinux.org/package/main/x86_64/lua-turbo (running turbo :) )

**Comment by kernelsauce** [comment]
Thank you.
