### ISSUE TITLE
Nested Inverted Sections

### ISSUE THREAD

**Issue by clandmeter** [kernelsauce/turbo#223]
When I try the below code in lustache, lustache will output:
no rows

But when i try this in turbo mustache it will output:
no foobar 
no rows

Is this a bug? if not, Is it possible to disable child sections when the parent is disabled?

```
local model = {
    rows = false
}

local tpl = [[
    {{#rows}}
        rows
        {{#foobar}} foobar {{/foobar}}
        {{^foobar}} no foobar {{/foobar}}
    {{/rows}}
    {{^rows}} no rows {{/rows}}
]]
```

**Comment by kernelsauce** [comment]
Its a bug.

**Comment by kernelsauce** [comment]
Fixed in master now :).
