### ISSUE TITLE
Looking for new maintainer for Turbo

### ISSUE THREAD

**Issue by kernelsauce** [kernelsauce/turbo#228]
Hello all.

Due to personal reasons I no longer have the time to follow up Turbo. I feel the project deserves to live on as it has quite a few users.

Therefore I am looking for new maintainer(s). The Github repo will be converted into a organization as a part of this. And no I'm not completely stepping down, but I simply do not have the time to fully administrate and do all of the things that should be done for a serious project.

If you are interested please reply here or by mail jhnabrhmsn@gmail.com.

**Comment by luastoned** [comment]
I'm not sure if I would be up to the task of fully maintaining the project.

What parts of your current work do you want to keep doing?

**Comment by voltagex** [comment]
It may be as simple as adding a few other people as contributors to the git repo.

Is there a solid TODO list for Turbo?

**Comment by kernelsauce** [comment]
Not really, there used to be for v2.0. That is now released so there is no next in line feature list/TODO. I have simply not had the time to commit to something like that now. Hence why Im looking for new people to help out :).

**Comment by kernelsauce** [comment]
@luastoned Well, anything really. I would like to continue working on it from time to time, but I can't afford the time that Turbo requires to be developed further. At this point its just about fixing critical bugs etc.
