### ISSUE TITLE
Case sensitive header fields

### ISSUE THREAD

**Issue by mvitez** [kernelsauce/turbo#235]
First of all thank you for this library. I just wanted to inform you of this problem:

Header fields names like "Content-Type" or "Content-Length" are searched by Turbo with case-sensitive comparison, which is wrong (RFC2616 / 4.2), so turbo does not work with other libraries, like e.g. node request, which sends "content-type" instead of "Content-Type".

**Comment by kernelsauce** [comment]
If that is indeed the case then it is a bug. It is supposed to support any case... I will look at it.

**Comment by mvitez** [comment]
Ok, thank you. I solved this problem by simply changing the default behaviour of httputil.HTTPParser:get:

Line 304 of httputil.lua becomes
if caseinsensitive == nil or caseinsensitive then
instead of
if caseinsensitive then

**Comment by kernelsauce** [comment]
That would do the trick ;). I'm going to review what would the best solution. I thought all places where we get headers were done case insensitive already...

**Comment by kernelsauce** [comment]
Now available on LuaRocks as v2.0.2.
