### ISSUE TITLE
WebSocketClient Connection Upgrade

### ISSUE THREAD

**Issue by luastoned** [kernelsauce/turbo#240]
I was playing with [LeapMotions](https://www.leapmotion.com/) websocket server and noticed that I got following error:

    [W 2015/12/02 15:56:34] [async.lua] GET localhost:6437/v6.json => 400 Bad Request 1015ms
    [E 2015/12/02 15:56:34] Excpected 101, was 400, can not upgrade.

After fiddling with WireShark and loopback magic I found the missing part:

    modify_headers = function(self, headers)
    	headers:add("Connection", "Upgrade")
    end

Not sure if this is a standard or not but it should be noticed somewhere.

**Comment by kernelsauce** [comment]
Thanks for the report Gregor. I have fixed it in master. Will create a new version once I have investigated #239 and #237 too.
