### ISSUE TITLE
websocket server do not send data

### ISSUE THREAD

**Issue by yurayko** [kernelsauce/turbo#241]
Server:
```lua
_G.TURBO_SSL = true
local turbo = require "turbo"

local WSExHandler = class("WSExHandler", turbo.websocket.WebSocketHandler)

function WSExHandler:on_message(msg)
    turbo.log.notice(string.format("%s", msg))
    self:write_message("Hello World.")
    self:close()
end

turbo.web.Application({{"^/ws$", WSExHandler}}):listen(8888)
turbo.ioloop.instance():start()
```
Client:
```lua
_G.TURBO_SSL = true
local turbo = require "turbo"

turbo.ioloop.instance():add_callback(function()
    turbo.websocket.WebSocketClient("ws://127.0.0.1:8888/ws", {
        on_connect = function(self)
            self:write_message("Hello World!")
        end,
        on_message = function(self, msg)
            print(msg)
        end,
        on_error = function(self, code, reason)
            print(code, reason)
        end
    })
end):start()
```

Client side did not receive "Hello World." from server (and close packet too).

**Comment by kernelsauce** [comment]
Works for me. So does the tests... What version are you running and what OS are you running?

<img width="1337" alt="screen shot 2015-12-08 at 19 56 37" src="https://cloud.githubusercontent.com/assets/1081754/11665164/29febdcc-9de6-11e5-8b02-b6f1fa4e642b.png">

**Comment by yurayko** [comment]
Debian amd64 jessie luajit 2.0.3+dfsg-3
Do you test my code? In your server output no have a "Hello World!" from client.

**Comment by kernelsauce** [comment]
Hi, there seems to be a race in that you can close the connection before the last message has actually been sent. I will fix that.

**Comment by kernelsauce** [comment]
Fixed now.
