### ISSUE TITLE
StaticFileHandler truncates updated file

### ISSUE THREAD

**Issue by Thomas12** [kernelsauce/turbo#247]
Hi,

I run version 0x020004 and the StaticFileHandler does not serve an updated file correctly that is longer than the inital one it has served. Platform (Luajit 2.1 beta on Banana Pro).

_G.TURBO_STATIC_MAX=-1;

File:

test.dat = "ABCDE"

served 1st time: ABCDE

update test.dat to "123ABCDE"

served 2nd time: 123AB instead of 123ABCDE

Kind regards,

Thomas

**Comment by kernelsauce** [comment]
Yes, static file handler only checks file once. I can add a option to allow
reloads, if wanted.
ons. 17. feb. 2016 kl. 12.36 skrev Thomas12 <notifications@github.com>:

> Hi,
>
> I run version 0x020004 and the StaticFileHandler does not serve an updated
> file correctly that is longer than the inital one it has served. Platform
> (Luajit 2.1 beta on Banana Pro).
>
> _G.TURBO_STATIC_MAX=-1;
>
> File:
>
> test.dat = "ABCDE"
>
> served 1st time: ABCDE
>
> update test.dat to "123ABCDE"
>
> served 2nd time: 123AB instead of 123ABCDE
>
> Kind regards,
>
> Thomas
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kernelsauce/turbo/issues/247>.
>
-- 
Mvh / Best regards
John Abrahamsen
Tlf/Phone: (+47) 941 35 009

**Comment by Thomas12** [comment]
Yes, that would be very nice as I am developing an application which also has static content that needs to be changed during development/testing, currently I have to restart turbolua each time :-(

**Comment by markuman** [comment]
What about using the [turbovisor](http://turbo.readthedocs.org/en/latest/turbovisor.html)?

**Comment by Thomas12** [comment]
A very interesting option.

I am working on a bit difficult setup with 2 browsers open and connected over websockets.
A restart would drop them. Ok I have an automatic reconnect but it costs time.

I didn't know that this was intentional, I really thought it was a bug. But on the other 
side you cannot check a filesize condition without the "expensive" stat :-)

How about this:

if (_G.TURBO_STATIC_MAX<1) then
  self.files = {}
end;

in the first line of
web._StaticWebCache:get_file(path)

Means: If caching is intentionally disabled at all, also stat files every time.

**Comment by kernelsauce** [comment]
Yeah, I will add that.
