### ISSUE TITLE
Question: How to bind to multiple ports/ips w/ and w/o SSL?

### ISSUE THREAD

**Issue by Thomas12** [kernelsauce/turbo#249]
Hi,

how can I bind one server to port 80 http and port 443 https at the same time? Is that possible? Tried with 2x listen, but SSL does not work then.

app:listen(80, "0.0.0.0", {max_body_size=1024*1024*100})
app:listen(443, "0.0.0.0", nil, {
    ssl_options = {
        key_file = "./sslkeys/server.key",
        cert_file = "./sslkeys/server.crt"
    }
})

Thank you!

Thomas

**Comment by kernelsauce** [comment]
Hi. You have to use two HTTPServer instances that you feed your application object :).

`
http_server_80 = httpserver.HTTPServer(application)
http_server:listen(80)
http_server_443 = httpserver.HTTPServer(application)
http_server_443:listen(443)

ioloop_instance:start()
`

**Comment by Thomas12** [comment]
Thank you, it works!
