### ISSUE TITLE
Uploading (post) and garbage collection

### ISSUE THREAD

**Issue by markuman** [kernelsauce/turbo#252]
I want to use Turbolua with a webform to upload files (at onces, no chunked upload).

Here is my `main.lua` and `upload.html`: https://gist.github.com/markuman/9f280b11d8eb602ae903

This works, but after uploading several files of medium size, it  can be observed that the used memory is growing and growing ... until it hits `/usr/local/share/lua/5.1/turbo/structs/buffer.lua:75: No memory`.
So how to release the memory?

**Comment by yurayko** [comment]
Try to insert  collectgarbage()
before self:finish()

**Comment by markuman** [comment]
Yes, that works fine. Thx!
