### ISSUE TITLE
Question: How to unbind/release used ports?

### ISSUE THREAD

**Issue by Thomas12** [kernelsauce/turbo#254]
I try to program a restart feature with execvp, currently it fails as after I do a 

turbo.ioloop.instance():close()

and try to restart turbolua within the same lua script and instance via execvp, I get a: "Could not bind to address. Address already in use."

Is there a way to unbind / release the addresses that turbo has used immediately after it was closed by turbo.ioloop.instance():close()?

A wait with sleep (5 seconds) within the program after ..:close() did not help.

When the whole lua script terminates, then a restart is no problem - I am looking for a way to release the used ports (80, 443) while the program is still running but I have terminated turbolua via turbo.ioloop.instance():close().

Thank you very much!

Thomas

**Comment by kernelsauce** [comment]
Hi. You should use HTTPServer and feed it at a Application object. The HTTPServer extends the TCPServer which you can :close() to unbind the ports used. Doing Application:listen() does not support this unfortunately.
