### ISSUE TITLE
websocket problem with interval

### ISSUE THREAD

**Issue by Thomas12** [kernelsauce/turbo#255]
Hi,

I'm using websockets to send/receive json data.
It is divided into 2 parts.

1. with an ioloop interval I am broadcasting a websocket message every second to all clients
2. clients can send normal websocket requests handled in on_message function

What works?

-clients can receive the broadcasts sent via interval from the server without problems
-clients can send normal websocket requests handeld by on_message but only as long as on_message never answers back with self:write_message

What does not work?
-as soon as the server sends data back to the client in on_message via self:write_message, the server does no longer process incoming websocket requests from the client, but the outgoing broadcast via interval to the clients still works.

Commenting out the interval broadcast resolves the problem, I can then send requests to the server and the server processes them and can answer back without problems. But I would like to use the broadcasts in the interval, too.

Question: Is this a bug or a limitation? As the server is singlethreaded I don't see the problem or the difference between:

-2 subsequent broadcasts done in the interval which work well 
and
-one broadcast in the interval followed by the answer back to the client in on_message (or vice-versa, I don't know what order causes the problem), which surprisingly leads to non-processing of further incoming websocket requests coming from the client. on_message gets no longer triggered then, but in tcpdump on the server side and in the websocket sniffer browser plugin I see that the browser still sends websocket requests to the server when I click for example a button on the website.

But both (interval broadcast and answer in on_message) is in the end realized via self:write_message().

Have you an idea what can be wrong? No errors on the browsers network/javascript console, no errors on server side ssh console.

Thank you!

Thomas

**Comment by kernelsauce** [comment]
Maybe you can provide an example code snippet. Im having a hard time
understanding what you are trying to do.

fre. 18. mar. 2016 kl. 11.34 skrev Thomas12 <notifications@github.com>:

> Hi,
>
> I'm using websockets to send/receive json data.
> It is divided into 2 parts.
>
>    1. with an ioloop interval I am broadcasting a websocket message every
>    second to all clients
>    2. clients can send normal websocket requests handled in on_message
>    function
>
> What works?
>
> -clients can receive the broadcasts sent via interval from the server
> without problems
> -clients can send normal websocket requests handeld by on_message but only
> as long as on_message never answers back with self:write_message
>
> What does not work?
> -as soon as the server sends data back to the client in on_message via
> self:write_message, the server does no longer process incoming websocket
> requests from the client, but the outgoing broadcast via interval to the
> clients still works.
>
> Commenting out the interval broadcast resolves the problem, I can then
> send requests to the server and the server processes them and can answer
> back without problems. But I would like to use the broadcasts in the
> interval, too.
>
> Question: Is this a bug or a limitation? As the server is singlethreaded I
> don't see the problem or the difference between:
>
> -2 subsequent broadcasts done in the interval which work well
> and
> -one broadcast in the interval followed by the answer back to the client
> in on_message (or vice-versa, I don't know what order causes the problem),
> which surprisingly leads to non-processing of further incoming websocket
> requests coming from the client. on_message gets no longer triggered then,
> but in tcpdump on the server side and in the websocket sniffer browser
> plugin I see that the browser still sends websocket requests to the server
> when I click for example a button on the website.
>
> But both (interval broadcast and answer in on_message) is in the end
> realized via self:write_message().
>
> Have you an idea what can be wrong? No errors on the browsers
> network/javascript console, no errors on server side ssh console.
>
> Thank you!
>
> Thomas
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/kernelsauce/turbo/issues/255>
>
-- 
Mvh / Best regards
John Abrahamsen
Tlf/Phone: (+47) 941 35 009

**Comment by Thomas12** [comment]
Thank you very much for your fast feedback! 
Strange, I created an example code based on my observation but this stripped down version doesn't have that particular problem. Have to investigate further...

**Comment by Thomas12** [comment]
In essence the problem seems to be that messages I send via websockets from the server-side using write_message can sometimes collide with boradcasts (nothing other than also write_messages, just many to different destinations) that I send from within a set_interval from the server-side, that means that another write_message attempt is made while the previous one hasn't finished yet, resulting in stalls when trying to receive any more websocket-data on the server side.

How can I avoid that?

I could use mutexes but they just block/eat/waste time better spent in the ioloop to get all the waiting jobs done.

Is there an easy solution? Have you some sort of a suspend-function in favor of letting ioloop do its jobs for xxx mseconds? (A wait that doesn't block the loop)?

**Comment by kernelsauce** [comment]
You can simply use coroutine.yield() to turn execution back to the io loop. But I dont think this will solve anything.  There shouldn't be any issue to use self:write_message before the previous one finishes...

**Comment by kernelsauce** [comment]
Were you able to create a example for this? @Thomas12

**Comment by Thomas12** [comment]
Unfortunately not, I tried to create a stripped-down demo but the problem vanished then. My workaround is to have a not so elegant and not 100% perfect selfmade "mutex" with a sleep-while-loop to be sure a broadcast /write_message has finished before a new one is attempted.
