### ISSUE TITLE
example from turbo.iosimple  hangs with an unresolved name

### ISSUE THREAD

**Issue by yurayko** [kernelsauce/turbo#257]
If we have
```
$host no.turbolua.org
Host no.turbolua.org not found: 3(NXDOMAIN)
```
then
```
#!/usr/bin/luajit

_G.TURBO_SSL = true
local turbo = require 'turbo'

turbo.ioloop.instance():add_callback(function()
    local stream = turbo.iosimple.dial("tcp://no.turbolua.org:80")
    stream:write("GET / HTTP/1.0\r\n\r\n")

    local data = stream:read_until_close()
    print(data)

    turbo.ioloop.instance():close()
end):start()
```
hangs forever

**Comment by kernelsauce** [comment]
Good catch. Its a unhandled error in IOSimple :). I will fix this.

tir. 22. mar. 2016 kl. 12.48 skrev yurayko <notifications@github.com>:

> If we have
>
> $host no.turbolua.org
> Host no.turbolua.org not found: 3(NXDOMAIN)
>
> then
>
> #!/usr/bin/luajit
>
> _G.TURBO_SSL = true
> local turbo = require 'turbo'
>
> turbo.ioloop.instance():add_callback(function()
>     local stream = turbo.iosimple.dial("tcp://no.turbolua.org:80")
>     stream:write("GET / HTTP/1.0\r\n\r\n")
>
>     local data = stream:read_until_close()
>     print(data)
>
>     turbo.ioloop.instance():close()
> end):start()
>
> hangs forever
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/kernelsauce/turbo/issues/257>
>
-- 
Mvh / Best regards
John Abrahamsen
Tlf/Phone: (+47) 941 35 009

**Comment by kernelsauce** [comment]
Fix is in pipeline.

**Comment by kernelsauce** [comment]
This is fixed now :).
