### ISSUE TITLE
Mustache templating syntax sugar/Context switching

### ISSUE THREAD

**Issue by max1220** [kernelsauce/turbo#258]
It would be cool to be able have a table like:
```lua
t = {
  foo = "123",
  bar = {hello="world", world="hello"}
}
```

and a template like:
```mustache
I can haz numberz: {{foo}}
{{bar.world}} {{bar.hello}}
```

or even just:
```mustache
I can haz numberz: {{foo}}
{{#bar}}{{world}} {{hello}}{{/bar}}
```
(Switching context to "bar", so "world" and "hello" are aviable)

and then obviously have them render as:
```
I can haz numberz: 123
hello world
```
(As it would be aviable in [Lustache](http://olivinelabs.com/lustache/).)

I have written a small(and verry unsafe) hack to get the dot-behaviour:
[mustache_hack.lua](https://github.com/kernelsauce/turbo/files/197009/mustache_hack.lua.txt)
[test.lua](https://github.com/kernelsauce/turbo/files/197010/test.lua.txt)

**Comment by kernelsauce** [comment]
Turbo Mustache only supports the Mustache spec.
