### ISSUE TITLE
Persistent HTTPClient connections

### ISSUE THREAD

**Issue by wranai** [kernelsauce/turbo#264]
I can see there already is a `keep_alive` flag for `fetch()`, which keeps the iostream open upon finalization. If I set `in_progress` to false, I can do another fetch and it works, but it does so by opening a new connection first, even if was kept alive and could be re-used; it's rather wasteful, especially for HTTPS. I need to connect to only one server, and I think it's not unusual that we just need to access one or two APIs, so being able to re-use the connection would be very useful.

**Comment by kernelsauce** [comment]
Hi. Yes that is a drawback indeed. However theres not much work to do to make it use persistent connections... I can not say when I get the time to implement it though.

**Comment by kernelsauce** [comment]
By setting the keep-alive flag you should now be able to reuse connection for http and https :).
