### ISSUE TITLE
ssl options not working in non-linux machine

### ISSUE THREAD

**Issue by santhosh-tekuri** [kernelsauce/turbo#269]
I am doing development on mac osx. and noticed that ssl is not working. 
as instructed in documentation i enabled luasec usage. still not working.

after digging into sources, i see
```lua
if self.ssl_options and platform.__LINUX__ then
```
at https://github.com/kernelsauce/turbo/blob/master/turbo/tcpserver.lua#L57

we are planning to use our program on PPC. so ssl will not work there as it is non __LINUX__

**Comment by kernelsauce** [comment]
The issues is that non-Linux uses LuaSec, and that just doesn't have the options that Turbo can offer when using OpenSSL directly. This is a limitation. If you feel like it you can contribute to LuaSec and fix that limitation.
