### ISSUE TITLE
Question: HTTPClient How to get ssl certificate details?

### ISSUE THREAD

**Issue by Thomas12** [kernelsauce/turbo#273]
I am testing turbo.async.HTTPClient():fetch and looking for a way to get the server's certificate details of the https-connection like issuer, common name, serial number, validity, etc.

Thank you very much!

**Comment by kernelsauce** [comment]
Can not be done currently. You can probably hack it by getting at the SSL struct in the iostream object used in HTTPClient. You would need to add c defs for the functions needed to extract the details from OpenSSL...
