### ISSUE TITLE
Please support TLS in server

### ISSUE THREAD

**Issue by Thomas12** [kernelsauce/turbo#290]
It seems that all recent browsers deny a connection to turbolua server over https (message: Please enable TLS / SSL_ERROR_NO_CYPHER_OVERLAP).

Could you please implement TLS on the turbolua server side?

Thank you!

**Comment by kernelsauce** [comment]
Which version of OpenSSL are you using?

TLS 1.2 is supported.

**Comment by Thomas12** [comment]
Sorry sorry!
That was my fault, that was a side effect of my attempt to get SNI working.
