### ISSUE TITLE
HTTPClient with no internet blocks instance loop

### ISSUE THREAD

**Issue by Thomas12** [kernelsauce/turbo#292]
Trying to make a get-request to another website with no internet available blocks the whole ioloop.instance for about 30 seconds. In the end the error is: "Error -3 : Could not connect. Name or service not known."

Trying the same with internet but invalid domain, gives the same error but within 1 second.

Is there a blocking DNS-lookup taking so much time as no DNS is found and turbolua does the DNS-lookup the blocking way?

See test-script below.

    #!/usr/bin/env /usr/local/bin/luajit
    
    _G.TURBO_SSL = true -- Enable SSL
    
    local turbo = require "turbo"
    turbo.log.categories.success = false
    
    local url = arg[1] -- First arg should be URL.
    
    local tio = turbo.ioloop.instance()
    
    i=0
    function myfunc()
    print("MF="..i)
    i=i+1
    end
    
    tio:set_interval(1000, myfunc);
    
    tio:add_callback(function()
        -- Must place everything in a IOLoop callback.
            cl=turbo.async.HTTPClient();
            ssl_options={}
            ssl_options['verify_ca']=true
            cl:initialize(ssl_options, nil, 8192);
    
        local res = coroutine.yield(
            cl:fetch(url, {
                           request_timeout=15,
                           connect_timeout=10,
                           user_agent=Client
                  })
            )
    
        if res.error or res.headers:get_status_code() ~= 200 then
          print "HTTP Error!";
          return
        else
          print("Code="..res['code'])
          print("Body="..res['body'])
        end
    end)
  
    tio:start()

**Comment by kernelsauce** [comment]
You are correct, it does block.  I will create a fix :).

**Comment by kernelsauce** [comment]
Please check out branch async-dns and test your things :).

**Comment by Thomas12** [comment]
Thank you a lot for the fast fix! It works very well.

There is just one (cosmetic?) thing, don't know if it is worth to be mentioned at all, see below.

Is it ok to have the second error and warning or should that be cancelled/aborted as soon as the connect timeout was hit?
Is it just a cosmetic thing or could that have some unwanted side effects?

Thank you again!

Thomas

_____________________________________
MF=0
MF=1
MF=2
MF=3
MF=4
MF=5
MF=6
MF=7
MF=8
[W 2016/11/16 18:59:34] [async.lua] Connect timed out after 10 secs. GET github.com/
[E 2016/11/16 18:59:34] [async.lua] Error code -5. Connect timed out after 10 secs
HTTP Error!
MF=9
MF=10
MF=11
MF=12
MF=13
MF=14
MF=15
MF=16
MF=17
MF=18
MF=19
[E 2016/11/16 18:59:44] [async.lua] Error code -3. Could not connect:
[W 2016/11/16 18:59:44] [ioloop.lua] Trying to finalize a coroutine context
            that there are no reference to.
MF=20
MF=21
MF=22
MF=23
MF=24

**Comment by kernelsauce** [comment]
Seems the connect timeout doesn't work so good in the async client when its closed in the IOStream. I will fix that.

**Comment by kernelsauce** [comment]
This should be fixed in 2.1 :).
