### ISSUE TITLE
Feature request: Unified console text output

### ISSUE THREAD

**Issue by Thomas12** [kernelsauce/turbo#294]
Could you please implement a function that is triggered whenever a console text output from turbolua occurs?

-stacktraces on errors
-normal logs/warnings

function on_console_output(message, mtype)
 --here I can log/save all output messages depending on their parameters: warning, stacktrace, etc.
 --if return = true then also print this message to console, if false suppress console text output
end 

Thank you!

**Comment by kernelsauce** [comment]
This can be done pretty easily by reimplementing turbo.log.* functions.

https://turbo.readthedocs.io/en/latest/log.html

If you do that your functions will be called instead of the builtin´s.
