### ISSUE TITLE
Question: conection to MariaDB and Redis

### ISSUE THREAD

**Issue by GeorgeVV** [kernelsauce/turbo#301]
Hello John,
     I've installed the turbo lua and I've done some tests. 
     All is ok but It is important to have un conection to Redis and MariaDB.   	 
     What I can connect turbo to MariaDB and Redis ?. I see that there is a module for Turbo: turboredis but it is unmanteined.
      My idea is to use redis-lua (author : Daniele Alessandri) because I've done some tests with this and it works. Can I use redis-lua for example ?.		 
	 
     Thank you for your advice.

**Comment by kernelsauce** [comment]
Yes, you can use any modules you like :).

**Comment by GeorgeVV** [comment]
Thank you!.

Finally I use redis and luasql.mysql

   local redis = require('redis')
   local luasql= require('luasql.mysql')
   ...

   I have had some problems (with luajit, luarocks); I had two versions of Lua installed in my Linux.
   Now, I have 5.1.5 only.   It works !.
