### ISSUE TITLE
Issues with the 2.1.1 luarocks install

### ISSUE THREAD

**Issue by jchassoul** [kernelsauce/turbo#312]
Hi there!

I'm getting the following error after trying to require ("turbo") I notice the version bump, I don't know if it's related, it caught my attention, I've tested it in different fresh installed instances, it's probably easy to reproduce, I'm using torch easy-install to get my luajit and rocks.

I can help with more testing and stuff (= thanks for all turbo is awesome.

require("turbo")
/opt/torch/install/share/lua/5.1/trepl/init.lua:389: /opt/torch/install/share/lua/5.1/trepl/init.lua:389: /opt/torch/install/share/lua/5.1/trepl/init.lua:389: /opt/torch/install/share/lua/5.1/trepl/init.lua:389: /opt/torch/install/share/lua/5.1/trepl/init.lua:389: /usr/local/share/lua/5.1/turbo/cdef.lua:211: attempt to redefine 'sigval' at line 8
stack traceback:
	[C]: in function 'error'
	/opt/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	[string "_RESULT={require("turbo")}"]:1: in main chunk
	[C]: in function 'xpcall'
	/opt/torch/install/share/lua/5.1/trepl/init.lua:661: in function 'repl'
	/opt/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:204: in main chunk
	[C]: at 0x00405d50

**Comment by kernelsauce** [comment]
Probably because master contained some fixes for this stuff and they were applied in the new release. Its easy to fix. I recommend using the older version until fixed.

**Comment by jchassoul** [comment]
Thanks for the response, will take your advice.
