### ISSUE TITLE
Build fail while installing

### ISSUE THREAD

**Issue by edubart** [kernelsauce/turbo#313]
#When doing `luarocks install turbo` I get the following error:

``
http_parser.c: In function ‘http_parser_parse_url’:
http_parser.c:2096:18: error: this statement may fall through [-Werror=implicit-fallthrough=]
         found_at = 1;
         ~~~~~~~~~^~~
http_parser.c:2099:7: note: here
       case s_req_server:
``

This is just a warning being treated as an error, please remove -Werror from the makefile when installing, new warnings usually appears with new GCC releases (I'm using gcc 7.1.1).

**Comment by kernelsauce** [comment]
Fixed in master.
