### ISSUE TITLE
[Suggestion] Integrate turbolua  with sqlite3 

### ISSUE THREAD

**Issue by brickcap** [kernelsauce/turbo#317]
Hello,

Do you think it would be a good idea to ship turbo with sqlite? There is some precedent for doing this. A framework called [BHCS stack](http://www.learnbchs.org/) uses sqlite as the default storage engine. 

[lsqlite3](https://luarocks.org/modules/dougcurrie/lsqlite3complete) by Doug Currie is the most feature complete implementation in lua. The lib is pretty small only ~797kb in size. I've used in a couple of experiments my self and it seems to work really well as a drop in. Not sure if we'd need to make some changes to make it more compatible with the concurrency model of turbo?   

Would love to hear your thoughts on this. 

BTW This issue was also discussed on the [Openresty forums](https://groups.google.com/forum/#!topic/openresty-en/lUH10YE_6Z8) it may provide some additional context. 

Thank you very much for creating turbo!

**Comment by szbnwer** [comment]
hi :)

if it's not hardcoded in building, then i'd like it - so completely removeable with a compiler flag (btw i'm still a beginner with turbo, but i already like it as its kinda lightweight)

thx 4 the great matery 4 everyone involved! :)

**Comment by kernelsauce** [comment]
I don't really see the need to weigh down Turbo with these things to be honest. Turbo is very small, adding lsqlite3 will probably triple its size. I would recommend you to just compile it yourself or use luarockt...

Closing.
