### ISSUE TITLE
Turbolua.org is gone

### ISSUE THREAD

**Issue by kwaping** [kernelsauce/turbo#325]
You should either remove references to turbolua.org or bring it back to life.

**Comment by max1220** [comment]
See: https://github.com/kernelsauce/turbo/issues/320
https://github.com/kernelsauce/turbo/issues/322

**Comment by kernelsauce** [comment]
Removed references.

**Comment by soccermitchy** [comment]
There's still one place pointing at turbolua.org on the repo: ![At the top of the repo main page](https://i.imgur.com/Cc1LdbQ.png)

**Comment by kernelsauce** [comment]
Thanks @soccermitchy. Fixed.
