### ISSUE TITLE
npm installation

### ISSUE THREAD

**Issue by stevermeister** [kernelsauce/turbo#327]
> luarocks install turbo

??
why not install via npm?

**Comment by max1220** [comment]
Because it's not a node application? AFAIK, it does not even include any javascript except in the examples.

**Comment by stevermeister** [comment]
sorry, it was a name collision (name collision for https://medium.com/@ericsimons/introducing-turbo-5x-faster-than-yarn-npm-and-runs-natively-in-browser-cc2c39715403)

this repo has really nothing to do with npm
